### ISSUE TITLE
how can I find the jwt endpoints?

### ISSUE THREAD

**Issue by MushiTheMoshi** [rookie-ninja/rk-boot#118]
**Describe the bug**
Hi,

First of all, really nice work done here.

After setting up jwt middleware I am unable to acess sw even when ignore is set to /sw, how can I know jwt endpoints to get access token?

**To Reproduce**
```
gin:
  - name: greeter                                          # Required
    port: 8080                                             # Required
    enabled: true                                          # Required
    commonService:
      enabled: true                                        # Optional, default: false
    sw:
      enabled: true                                        # Optional, default: false
    docs:
      enabled: true                                        # Optional, default: false
    middleware:
     jwt:
       enabled: true                                     # Optional, default: false
       ignorePrefix:                                      # Optional, default: []
         - "/sw"
```

**Expected behavior**
after ignoring /sw I should be able to access sw and retrieve endpoints to get jwt token

**Desktop (please complete the following information):**
 - OS: Linux
 - Brave
 - Version 

**Smartphone (please complete the following information):**
 - Version v2.2.3

**Comment by dongxuny** [comment]
@MushiTheMoshi Hi, there are couple of steps we need to do if we hope to authorize API with JWT in swagger.

I created a demo at [demo](https://github.com/rookie-ninja/rk-boot/tree/main/example/middleware/jwt/gin)

## Steps needs to follow for JWT in Swagger
- Swag comments which enables JWT security in code.
- Implement Login() handler which will generate custom JWT token for requests
- Authorize with JWT in swagger UI.

## Short demo
Please refer to code at [demo](https://github.com/rookie-ninja/rk-boot/tree/main/example/middleware/jwt/gin)

### boot.yaml
```yaml
---
gin:
  - name: greeter
    port: 8080
    enabled: true
    sw:
      enabled: true
    middleware:
      jwt:
        enabled: true
        ignore:
          - "/v1/login"
          - "/sw"
```

### main.go
[demo](https://github.com/rookie-ninja/rk-boot/tree/main/example/middleware/jwt/gin)

### Start server
```shell
go run main.go
```

### Access swagger UI
http://localhost:8080/sw

### Login
![login](https://user-images.githubusercontent.com/50768414/183700731-2d086287-b81e-4bfc-9e30-c05e64427eca.png)

### Authorize JWT in Swagger
Copy returned JWT token and authorize JWT
![authorise](https://user-images.githubusercontent.com/50768414/183700842-af4a365f-f167-41a7-b349-186b637c1a1c.png)

### Send /v1/whoami
![success](https://user-images.githubusercontent.com/50768414/183700874-33f6d8c2-c73c-44b3-a868-238d0ec7e51c.png)
