### ISSUE TITLE
Is there anyway to configure the default event log at stdout when starting app?

### ISSUE THREAD

**Issue by emilebui** [rookie-ninja/rk-boot#126]
Hi, is there any possible way to disable the stdout event log or configurate it to generate log in file instead when starting app

![image](https://user-images.githubusercontent.com/33470772/196594455-9a528e8f-f79b-44f0-b429-e78c73113a5b.png)

**Comment by dongxuny** [comment]
Here is the configuration of event log docs with Echo framework.

https://docs.rkdev.info/user-guide/web/echo/logging/#concept

In your case, I think bellow configuration will work.

```yaml
event:
  - name: my-event
    outputPaths: [""]   # set to empty if want to ignoring all event logs
echo:
  - name: greeter
    port: 8080
    enabled: true
    eventEntry: my-event
```
